config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :histories,  except: [ :destroy, :show, :edit, :update]
  resources :carts
  resources :productions do
    resources :users do
    	resources :carts
        end
  end
  resources :authors
  devise_for :users
  resources :users, except: [ :new, :create, :destroy ] do
    resources :carts
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to:'users#index'
  root to: 'productions#index'
end

app/models/author.rb
class Author < ApplicationRecord
  include Authority::Abilities
  has_many :productions, dependent: :destroy
  validates :fullname,  presence: true, uniqueness: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || !current_user.role?
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || !current_user.role?
  end

  # POST /authors
  # POST /authors.json
  def create
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || !current_user.role?
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || !current_user.role?
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || !current_user.role?
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
      @productions = @author.productions
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:fullname)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<div class="container">
<div class="row">
        <div class="col-md-8 col-md-offset-4">
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_field :fullname, id: :author_fullname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div></div></div>

app/views/authors/edit.html.erb
<div class="container">
<div class="row">
 <div class="col-md-8 col-md-offset-4"><h1>Editing Author</h1></div></div>
</div>
<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.fullname %></td>
        <td><%= link_to 'Show', author %></td>
        <% if current_user && current_user.role? %><td><%= link_to 'Edit', edit_author_path(author) %></td><% end %>
        <% if current_user && current_user.role? %><td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && current_user.role? %><%= link_to 'New Author', new_author_path %><% end %><br>
<%= link_to 'Main page', productions_path %>
</div>

app/views/authors/new.html.erb
<div class="container">
<div class="row">
 <div class="col-md-8 col-md-offset-4">
<h1>New Author</h1></div></div></div>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<div class="container">
<div class="row">
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @author.fullname %><br>
</p>
<% if  @productions.count!=0%>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Author</th>
      <th>Count</th>
      <th>Pages</th>
      <th colspan="3"></th>
    </tr>
  </thead>
   <tbody>
    <% @productions.each do |production| %>
      <tr>
        <td><%= production.title %></td>
        <td><%= number_to_currency(production.price) %></td>
        <td><%= production.author.fullname %></td>
        <td><%= production.count %></td>
        <td><%= production.pages %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<% if current_user && current_user.role? %><%= link_to 'Edit author', edit_author_path(@author) %> |<% end %>
<%= link_to 'Back', authors_path %></div></div>