config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :histories,  except: [ :destroy, :show, :edit, :update]
  resources :carts
  resources :productions do
    resources :users do
    	resources :carts
        end
  end
  resources :authors
  devise_for :users
  resources :users, except: [ :new, :create, :destroy ] do
    resources :carts
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to:'users#index'
  root to: 'productions#index'
end

app/models/production.rb
class Production < ApplicationRecord
  include Authority::Abilities
  belongs_to :author
  has_many :carts, dependent: :destroy
  validates :title,  presence: true, uniqueness: true
  has_many :histories, dependent: :destroy
end

app/controllers/productions_controller.rb
class ProductionsController < ApplicationController
  before_action :set_production, only: [:show, :edit, :update, :destroy]

  # GET /productions
  # GET /productions.json
  def index
    @productions = Production.all
    @users = User.all
    @carts = Cart.all
  end

  # GET /productions/1
  # GET /productions/1.json
  def show
  end

  # GET /productions/new
  def new
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || !current_user.role?
    @production = Production.new
    @authors = Author.all
  end

  # GET /productions/1/edit
  def edit
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || !current_user.role?
    @authors = Author.all
  end

  # POST /productions
  # POST /productions.json
  def create
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || !current_user.role?
    @production = Production.new(production_params)

    respond_to do |format|
      if @production.save
        format.html { redirect_to @production, notice: 'Production was successfully created.' }
        format.json { render :show, status: :created, location: @production }
      else
        format.html { render :new }
        format.json { render json: @production.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productions/1
  # PATCH/PUT /productions/1.json
  def update
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || !current_user.role?
    respond_to do |format|
      if @production.update(production_params)
        format.html { redirect_to @production, notice: 'Production was successfully updated.' }
        format.json { render :show, status: :ok, location: @production }
      else
        format.html { render :edit }
        format.json { render json: @production.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productions/1
  # DELETE /productions/1.json
  def destroy
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || !current_user.role?
    @production.destroy
    respond_to do |format|
      format.html { redirect_to productions_url, notice: 'Production was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_production
      @production = Production.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def production_params
      params.require(:production).permit(:title, :price, :author_id, :count, :pages)
    end
end

app/helpers/productions_helper.rb
module ProductionsHelper
end

app/views/productions/_form.html.erb
<div class="container">
<div class="row">
        <div class="col-md-8 col-md-offset-4"><%= form_with(model: production, local: true) do |form| %>
  <% if production.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(production.errors.count, "error") %> prohibited this production from being saved:</h2>

      <ul>
      <% production.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :production_title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :production_price %>
  </div>


  <div class="field">
    <%= form.label :author_id %>
    <%= form.select(:author_id) do %>
      <% @authors.each do |author1| %>
        <%= content_tag(:option, author1.fullname, value: author1.id) %>
     <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count, id: :production_count %>
  </div>

  <div class="field">
    <%= form.label :pages %>
    <%= form.number_field :pages, id: :production_pages %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %></div></div></div>

app/views/productions/edit.html.erb
<div class="container">
<div class="row">
 <div class="col-md-8 col-md-offset-4"><h1>Editing Production</h1></div></div></div>

<%= render 'form', production: @production %>

<%= link_to 'Show', @production %> |
<%= link_to 'Back', productions_path %>

app/views/productions/index.html.erb
<div class="container"><p id="notice"><%= notice %></p>

<h1>Welcome to our shop. Here you can choose and buy any book.</h1>
<% if current_user && current_user.role? %><%= link_to 'Home', users_path %> <br><% end %>
<% if current_user && !current_user.role? %><%= link_to 'Home', user_carts_path(current_user) %> <br><% end %>
<%= link_to 'Show all authors', authors_path %><br>
<% if current_user && current_user.role? %><%= link_to 'New book', new_production_path %><br><% end %>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Author</th>
      <th>Count</th>
      <th>Pages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productions.each do |production| %>
      <tr>
        <td><%= production.title %></td>
        <td><%= number_to_currency(production.price) %></td>
        <td><%= production.author.fullname %></td>
        <td><%= production.count %></td>
        <td><%= production.pages %></td>
        <td><%= link_to 'Show', production %></td>
        <% if current_user  && !current_user.role? %><td><%= link_to 'Add into basket', production_user_carts_path(production.id, current_user), method: :create, data: { confirm: 'Are you sure?' } %></td><% end %>
        <% if current_user && current_user.role? %><td><%= link_to 'Edit', edit_production_path(production) %></td><% end %>
        <% if current_user && current_user.role? %><td><%= link_to 'Destroy', production, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div></div></div>

app/views/productions/new.html.erb
<div class="container">
<div class="row">
        <div class="col-md-8 col-md-offset-4"><h1>New Production</h1></div></div></div>

<%= render 'form', production: @production %>

<%= link_to 'Back', productions_path %>

app/views/productions/show.html.erb
<div class="container">
<div class="row">
<div class="col-md-9 col-md-offset-4"><p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @production.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@production.price) %>
</p>

<p>
  <strong>Author:</strong>
  <%= @production.author.fullname %>
</p>

<p>
  <strong>Count:</strong>
  <%= @production.count %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @production.pages %>
</p>

<% if current_user && current_user.role? %><%= link_to 'Edit', edit_production_path(@production) %> |<% end %>
<%= link_to 'Back', productions_path %></div></div></div>