config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :histories,  except: [ :destroy, :show, :edit, :update]
  resources :carts
  resources :productions do
    resources :users do
    	resources :carts
        end
  end
  resources :authors
  devise_for :users
  resources :users, except: [ :new, :create, :destroy ] do
    resources :carts
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to:'users#index'
  root to: 'productions#index'
end

app/models/history.rb
class History < ApplicationRecord
  include Authority::Abilities
  self.authorizer_name = 'AdminAuthorizer'
  belongs_to :production
  belongs_to :user

  after_save :reculculate_count
    private
    def reculculate_count
      production.count =production.count-count
      production.save!
    end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
  end

  # GET /histories/new
  def new
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
  end

  # POST /histories
  # POST /histories.json
  def create
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:production_id, :user_id, :count, :sum)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_with(model: history, local: true) do |form| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :production_id %>
    <%= form.number_field :production_id, id: :history_production_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :history_user_id %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count, id: :history_count %>
  </div>

  <div class="field">
    <%= form.label :sum %>
    <%= form.number_field :sum, id: :history_sum %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<div class="container"><p id="notice"><%= notice %></p>

<h1>Histories</h1>

<table>
  <thead>
    <tr>
      <th>Production</th>
      <th>Count</th>
      <th>Sum</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.production.title %></td>
        <td><%= history.count %></td>
        <td><%= number_to_currency(history.sum) %></td>
        <td><%= history.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Home', user_carts_path(current_user) %><br>
<%= link_to 'Main page', productions_path %>
</div>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Production:</strong>
  <%= @history.production_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @history.user_id %>
</p>

<p>
  <strong>Count:</strong>
  <%= @history.count %>
</p>

<p>
  <strong>Sum:</strong>
  <%= @history.sum %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>