config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :histories,  except: [ :destroy, :show, :edit, :update]
  resources :carts
  resources :productions do
    resources :users do
    	resources :carts
        end
  end
  resources :authors
  devise_for :users
  resources :users, except: [ :new, :create, :destroy ] do
    resources :carts
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to:'users#index'
  root to: 'productions#index'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :production
  belongs_to :user
  include Authority::Abilities
  self.authorizer_name = 'AdminAuthorizer'

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
    @user=current_user
    @carts = Cart.where(user: @user)
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
      redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
  end

  # GET /carts/new
  def new
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
  end

  # POST /carts
  # POST /carts.json
  def create
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
    @cart = Cart.new()
    @cart = Cart.new(params.permit(:production_id, :user_id, :count, :sum))
    @carts = Cart.all
    respond_to do |format|
      if @carts.count==0
        @cart.save
        Cart.update(@cart.id, :user_id => @cart.user_id, :production_id => @cart.production_id, :sum =>@cart.production.price)
      else
        i=0
        while @carts.count>i && (@carts[i].user_id!=@cart.user_id || @carts[i].production_id!=@cart.production_id)
          i+=1
        end
        if  i!=@carts.count
          Cart.update(@carts[i].id, :user_id => @carts[i].user_id, :production_id => @carts[i].production_id, :count => @carts[i].count+1, :sum =>(@carts[i].count+1)*@carts[i].production.price)
        else
         @cart.save
        Cart.update(@cart.id, :user_id => @cart.user_id, :production_id => @cart.production_id, :sum =>@cart.production.price)
       end
     end
     format.html { redirect_to "/", notice: "The book has been successfully added"}
   end
 end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
    respond_to do |format|
      if @cart.update(cart_params) && @cart.production.count!=nil && @cart.production.count>@cart.count
        @history = History.new()
        @history.production=@cart.production
        @history.user=@cart.user
        @history.count=@cart.count
        @history.sum=@cart.count*@cart.production.price
        @history.save
        @cart.destroy
        format.html { redirect_to "/histories", notice: "Thank you for your purchase" }
      else
        format.html { redirect_to "/carts", notice: "The quantity of the book exceeds quantity at the warehouse" }
        format.html { render :edit}
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
      redirect_to "/", notice: "Sorry, You don't have enough rights" if current_user.nil? || current_user.role?
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:production_id, :user_id, :count, :sum)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<div class="container">
<div class="row">
        <div class="col-md-8 col-md-offset-4"><%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, id: :cart_user_id %>
  </div>

  <div class="field">
    <%= form.label :production_id %>
    <%= form.hidden_field :production_id, id: :cart_production_id%>
    <%= fields_for @cart.production do |f1| %>
      <%= f1.text_field :title %>
    <% end %>
  </div>


  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count, id: :cart_count %>
  </div>

  <div class="field">
    <%= form.hidden_field :sum %>
    <%= form.hidden_field :sum, id: :cart_sum %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>  </div>  </div>  </div>

app/views/carts/edit.html.erb
<div class="container">
<div class="row">
 <div class="col-md-8 col-md-offset-4"><h1>Buying book</h1></div></div>
</div>


<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<div class="container"><p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Production</th>
      <th>Count</th>
      <th>Sum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.production.title %></td>
        <td><%= cart.count %></td>
        <td><%= number_to_currency(cart.sum) %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Buy', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Show history', histories_path %><br>
<%= link_to 'Main page', productions_path %></div>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Production:</strong>
  <%= @cart.production_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @cart.user_id %>
</p>

<p>
  <strong>Count:</strong>
  <%= @cart.count %>
</p>

<p>
  <strong>Sum:</strong>
  <%= @cart.sum %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>